// Her birim: attack, defGeneral, defCavalry, defArcher, speed(dakika/kare), carry, population, cost, buildTime, requirement
const units = {
  spearman: {
    name: 'Mızrakçı',
    description: 'Süvari savunmasında güçlü piyade birimi.',
    attack: 10,
    defGeneral: 15,
    defCavalry: 45,
    defArcher: 20,
    speed: 18,
    carry: 25,
    population: 1,
    cost: { wood: 50, clay: 30, iron: 10 },
    buildTime: 1000,
    requirement: { barracks: 1 }
  },
  swordsman: {
    name: 'Kılıçlı',
    description: 'Güçlü genel savunma birimi.',
    attack: 25,
    defGeneral: 50,
    defCavalry: 25,
    defArcher: 30,
    speed: 22,
    carry: 15,
    population: 1,
    cost: { wood: 30, clay: 30, iron: 70 },
    buildTime: 1500,
    requirement: { barracks: 3, smithy: 1 }
  },
  axeman: {
    name: 'Baltacı',
    description: 'Güçlü saldırı piyade birimi.',
    attack: 40,
    defGeneral: 10,
    defCavalry: 5,
    defArcher: 10,
    speed: 18,
    carry: 10,
    population: 1,
    cost: { wood: 60, clay: 30, iron: 40 },
    buildTime: 1320,
    requirement: { barracks: 2, smithy: 2 }
  },
  lightCavalry: {
    name: 'Hafif Süvari',
    description: 'Hızlı keşif ve yağma birimi.',
    attack: 130,
    defGeneral: 30,
    defCavalry: 40,
    defArcher: 30,
    speed: 10,
    carry: 80,
    population: 4,
    cost: { wood: 125, clay: 100, iron: 250 },
    buildTime: 2000,
    requirement: { stable: 3 }
  },
  heavyCavalry: {
    name: 'Ağır Süvari',
    description: 'Güçlü saldırı ve savunma süvarisi.',
    attack: 150,
    defGeneral: 200,
    defCavalry: 80,
    defArcher: 180,
    speed: 11,
    carry: 50,
    population: 6,
    cost: { wood: 200, clay: 150, iron: 600 },
    buildTime: 2700,
    requirement: { stable: 10, smithy: 15 }
  },
  mountedArcher: {
    name: 'Atlı Okçu',
    description: 'Hızlı ve esnek okçu süvarisi.',
    attack: 120,
    defGeneral: 40,
    defCavalry: 30,
    defArcher: 50,
    speed: 10,
    carry: 50,
    population: 5,
    cost: { wood: 250, clay: 100, iron: 150 },
    buildTime: 2400,
    requirement: { stable: 5, smithy: 5 }
  },
  ram: {
    name: 'Koçbaşı',
    description: 'Sur yıkma kuşatma aleti.',
    attack: 2,
    defGeneral: 20,
    defCavalry: 50,
    defArcher: 20,
    speed: 30,
    carry: 0,
    population: 5,
    cost: { wood: 300, clay: 200, iron: 200 },
    buildTime: 4800,
    requirement: { workshop: 1 },
    wallDamage: true
  },
  catapult: {
    name: 'Mancınık',
    description: 'Binaları yıkan kuşatma silahı.',
    attack: 100,
    defGeneral: 100,
    defCavalry: 50,
    defArcher: 100,
    speed: 30,
    carry: 0,
    population: 8,
    cost: { wood: 320, clay: 400, iron: 100 },
    buildTime: 7200,
    requirement: { workshop: 2, smithy: 12 },
    buildingDamage: true
  },
  noble: {
    name: 'Soylu',
    description: 'Köylerin sadakatini düşürerek ele geçirir.',
    attack: 30,
    defGeneral: 100,
    defCavalry: 50,
    defArcher: 100,
    speed: 35,
    carry: 0,
    population: 100,
    cost: { wood: 40000, clay: 50000, iron: 50000 },
    buildTime: 18000,
    requirement: { academy: 1 },
    loyaltyReduction: true
  },
  paladin: {
    name: 'Paladin',
    description: 'Güçlü kahraman birimi. Her köyde bir tane.',
    attack: 150,
    defGeneral: 250,
    defCavalry: 400,
    defArcher: 150,
    speed: 10,
    carry: 100,
    population: 10,
    cost: { wood: 100, clay: 100, iron: 100 },
    buildTime: 36000,
    requirement: { barracks: 1 },
    unique: true,
    maxPerVillage: 1
  }
};

export default units;
